// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3mKG08LjrnZ5IbEHCqVUcPQ_iNdVSpu4',
    appId: '1:577426826958:android:ebce65dc113f068aa5d29f',
    messagingSenderId: '577426826958',
    projectId: 'turf-booking-fa28e',
    storageBucket: 'turf-booking-fa28e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzt7k-v1Ymo-MSuBS-laOdUk3AHFPqvfk',
    appId: '1:577426826958:ios:0cc91659d9fa00a2a5d29f',
    messagingSenderId: '577426826958',
    projectId: 'turf-booking-fa28e',
    storageBucket: 'turf-booking-fa28e.appspot.com',
    androidClientId: '577426826958-iuc4o29iujgd7bv5t87tf0tmkfic6lm5.apps.googleusercontent.com',
    iosClientId: '577426826958-gg0gvrtra3mmsj10vn1qugud4ul2tq6o.apps.googleusercontent.com',
    iosBundleId: 'com.example.turfBookingAdmin',
  );
}
